data:
  file_path: 'data/Marketing.csv'

email:
  sender_email: 'sender@mail.com'
  sender_name: 'Report Bot'
  recipient_email: 'recipient@mail.com'
  recipient_name: 'Marketing Team'
  subject: 'Weekly Report v2'

report:
  template_dir: 'templates'
  template_name: 'report_template_gmail.html'
  title: 'Marketing Spend Analysis'
  output_file: 'final_report.html'
